{{- if .Values.persistence.enabled }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  labels:
    app: {{ .Values.microservice.name }}
    type: local
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: {{ .Values.microservice.name }}
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
{{- end }}