apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.microservice.name }}
  namespace: {{ .Values.microservice.namespace }}
data:
  ENV: "prod"
  POSTGRES_HOST: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "postgres"
  OPTION_A: "Cats"
  OPTION_B: "Dogs"
  PORT: "80"